// Generated by BUCKLESCRIPT VERSION 4.0.8, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

var list_a = /* :: */[
  "a",
  /* :: */[
    "b",
    /* :: */[
      "c",
      /* :: */[
        "d",
        /* [] */0
      ]
    ]
  ]
];

var list_b = /* :: */[
  "a",
  /* [] */0
];

function last_two(_l) {
  while(true) {
    var l = _l;
    if (l) {
      var rest = l[1];
      if (rest) {
        if (rest[1]) {
          _l = rest;
          continue ;
        } else {
          return /* tuple */[
                  l[0],
                  rest[0]
                ];
        }
      } else {
        return undefined;
      }
    } else {
      return undefined;
    }
  };
}

console.log(Caml_obj.caml_equal(last_two(list_a), /* tuple */[
          "c",
          "d"
        ]));

console.log(last_two(list_b) === undefined);

exports.list_a = list_a;
exports.list_b = list_b;
exports.last_two = last_two;
/*  Not a pure module */
