// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


var list_a = /* :: */[
  /* "a" */97,
  /* :: */[
    /* "b" */98,
    /* :: */[
      /* "c" */99,
      /* :: */[
        /* "d" */100,
        /* [] */0
      ]
    ]
  ]
];

function length(_$staropt$star, _l, _param) {
  while(true) {
    var l = _l;
    var $staropt$star = _$staropt$star;
    var k = $staropt$star !== undefined ? $staropt$star : 0;
    if (l) {
      _param = /* () */0;
      _l = l[1];
      _$staropt$star = k + 1 | 0;
      continue ;
    } else {
      return k;
    }
  };
}

console.log(length(undefined, list_a, /* () */0) === 4);

exports.list_a = list_a;
exports.length = length;
/*  Not a pure module */
