// Generated by BUCKLESCRIPT VERSION 4.0.8, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

var list_a = /* :: */[
  /* "a" */97,
  /* :: */[
    /* "b" */98,
    /* :: */[
      /* "c" */99,
      /* :: */[
        /* "d" */100,
        /* [] */0
      ]
    ]
  ]
];

function at(_k, _l) {
  while(true) {
    var l = _l;
    var k = _k;
    if (l) {
      var match = k === 0;
      if (match) {
        return Caml_option.some(l[0]);
      } else {
        _l = l[1];
        _k = k - 1 | 0;
        continue ;
      }
    } else {
      return undefined;
    }
  };
}

console.log(Caml_obj.caml_equal(at(0, list_a), /* "a" */97));

console.log(Caml_obj.caml_equal(at(1, list_a), /* "b" */98));

console.log(Caml_obj.caml_equal(at(2, list_a), /* "c" */99));

console.log(at(1000, list_a) === undefined);

exports.list_a = list_a;
exports.at = at;
/*  Not a pure module */
