// Generated by BUCKLESCRIPT VERSION 4.0.8, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

var list_a = /* :: */[
  /* "a" */97,
  /* :: */[
    /* "b" */98,
    /* :: */[
      /* "c" */99,
      /* :: */[
        /* "d" */100,
        /* [] */0
      ]
    ]
  ]
];

function rev(l) {
  if (l) {
    var rest = l[1];
    var a = l[0];
    if (rest) {
      return Pervasives.$at(rev(rest), /* :: */[
                  a,
                  /* [] */0
                ]);
    } else {
      return /* :: */[
              a,
              /* [] */0
            ];
    }
  } else {
    return /* [] */0;
  }
}

console.log(Caml_obj.caml_equal(rev(list_a), List.rev(list_a)));

exports.list_a = list_a;
exports.rev = rev;
/*  Not a pure module */
